# Generated by Django 6.0.6 on 2026-06-20 09:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataAnalyze',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.CharField(max_length=50, verbose_name='data')),
                ('description', models.TextField(default='Обработаны данные', max_length=250, verbose_name='description')),
                ('type', models.CharField(default='Таблица', max_length=50, verbose_name='type')),
                ('analyzed', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Data Analyze',
                'db_table': 'past_year.data_analyze',
            },
        ),
        migrations.CreateModel(
            name='OnVacation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('surname', models.CharField(max_length=50, verbose_name='surname')),
                ('vacation_started', models.DateField(verbose_name='vacation_started')),
                ('vacation_endings', models.DateField(verbose_name='vacation_endings')),
            ],
            options={
                'verbose_name': 'Worker',
                'verbose_name_plural': 'Workers',
                'db_table': 'past_year.on_vacation',
            },
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('surname', models.CharField(max_length=50, verbose_name='surname')),
                ('data_checked_per_day', models.IntegerField(verbose_name='data_checked')),
                ('profile_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Worker',
                'verbose_name_plural': 'Workers',
                'db_table': 'past_year.workers',
            },
        ),
    ]
