[uwsgi]
module = config.wsgi:application
master=true
processes=4
threads=2
socket=/tmp/uwsgi.sock
chmod-socket=666
vacuum=true
die-on-term=true
py-autoreload = 1
harakiri = 20
max-requests = 5000